<a href="https://colab.research.google.com/github/disha2sinha/BASICS-OF-PROGRAMMING/blob/master/TwitterSentimentAnalysis(DataExploration).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Dataset as PANDAS Dataframe**

In [2]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

     |████████████████████████████████| 993kB 2.9MB/s
  Building wheel for PyDrive (setup.py) ... done

In [0]:
auth.authenticate_user()
gauth=GoogleAuth()
gauth.credentials=GoogleCredentials.get_application_default()
drive=GoogleDrive(gauth)

In [0]:
link='https://drive.google.com/open?id=15tIM6B4Up-2qFFfRUeC7N7turErE42S_'

In [5]:
fluff,id=link.split('=')
print(id)

15tIM6B4Up-2qFFfRUeC7N7turErE42S_

In [0]:
import pandas as pd

In [0]:
download=drive.CreateFile({'id':id})
download.GetContentFile('twitter_sentiment_data.csv')

In [8]:
df=pd.read_csv('twitter_sentiment_data.csv',engine='python')
df.head()

   0  ...  @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D
0  0  ...  is upset that he can't update his Facebook by ...
1  0  ...  @Kenichan I dived many times for the ball. Man...
2  0  ...    my whole body feels itchy and like its on fire
3  0  ...  @nationwideclass no, it's not behaving at all....
4  0  ...                      @Kwesidei not the whole crew

[5 rows x 6 columns]

In [9]:
df.rename(columns={'0':'Target','1467810369':'ID','Mon Apr 06 22:19:45 PDT 2009':'Time_Info','NO_QUERY':'Query','_TheSpecialOne_':'UN',df.columns[5]:'Comments'},inplace=True)
df

         Target  ...                                           Comments
0             0  ...  is upset that he can't update his Facebook by ...
1             0  ...  @Kenichan I dived many times for the ball. Man...
2             0  ...    my whole body feels itchy and like its on fire
3             0  ...  @nationwideclass no, it's not behaving at all....
4             0  ...                      @Kwesidei not the whole crew
5             0  ...                                        Need a hug
6             0  ...  @LOLTrish hey  long time no see! Yes.. Rains a...
7             0  ...               @Tatiana_K nope they didn't have it
8             0  ...                          @twittera que me muera ?
9             0  ...        spring break in plain city... it's snowing
10            0  ...                         I just re-pierced my ears
11            0  ...  @caregiving I couldn't bear to watch it.  And ...
12            0  ...  @octolinz16 It it counts, idk why I did either...
13            0  ...  @smarrison i would've been the first, but i di...
14            0  ...  @iamjazzyfizzle I wish I got to watch it with ...
15            0  ...  Hollis' death scene will hurt me severely to w...
16            0  ...                               about to file taxes
17            0  ...  @LettyA ahh ive always wanted to see rent  lov...
18            0  ...  @FakerPattyPattz Oh dear. Were you drinking ou...
19            0  ...  @alydesigns i was out most of the day so didn'...
20            0  ...  one of my friend called me, and asked to meet ...
21            0  ...   @angry_barista I baked you a cake but I ated it
22            0  ...             this week is not going as i had hoped
23            0  ...                         blagh class at 8 tomorrow
24            0  ...     I hate when I have to call and wake people up
25            0  ...  Just going to cry myself to sleep after watchi...
26            0  ...                             im sad now  Miss.Lilly
27            0  ...  ooooh.... LOL  that leslie.... and ok I won't ...
28            0  ...  Meh... Almost Lover is the exception... this t...
29            0  ...  some1 hacked my account on aim  now i have to ...
...         ...  ...                                                ...
1599969       4  ...  Thanks @eastwestchic &amp; @wangyip Thanks! Th...
1599970       4  ...  @marttn thanks Martin. not the most imaginativ...
1599971       4  ...          @MikeJonesPhoto Congrats Mike  Way to go!
1599972       4  ...  http://twitpic.com/7jp4n - OMG! Office Space.....
1599973       4  ...  @yrclndstnlvr ahaha nooo you were just away fr...
1599974       4  ...  @BizCoachDeb  Hey, I'm baack! And, thanks so m...
1599975       4  ...  @mattycus Yeah, my conscience would be clear i...
1599976       4  ...  @MayorDorisWolfe Thats my girl - dishing out t...
1599977       4  ...                          @shebbs123 i second that
1599978       4  ...                                     In the garden
1599979       4  ...  @myheartandmind jo jen by nemuselo zrovna té h...
1599980       4  ...  Another Commenting Contest! [;: Yay!!!  http:/...
1599981       4  ...  @thrillmesoon i figured out how to see my twee...
1599982       4  ...  @oxhot theri tomorrow, drinking coffee, talkin...
1599983       4  ...  You heard it here first -- We're having a girl...
1599984       4  ...  if ur the lead singer in a band, beware fallin...
1599985       4  ...              @tarayqueen too much ads on my blog.
1599986       4  ...  @La_r_a NEVEER  I think that you both will get...
1599987       4  ...  @Roy_Everitt ha- good job. that's right - we g...
1599988       4  ...                 @Ms_Hip_Hop im glad ur doing well
1599989       4  ...                              WOOOOO! Xbox is back
1599990       4  ...  @rmedina @LaTati Mmmm  That sounds absolutely ...
1599991       4  ...                  ReCoVeRiNg FrOm ThE lOnG wEeKeNd
1599992       4  ...                                  @SCOOBY_GRITBOYS
1599993       4  ...  @Cliff_Forster Yeah, that does work better tha...
1599994       4  ...  Just woke up. Having no school is the best fee...
1599995       4  ...  TheWDB.com - Very cool to hear old Walt interv...
1599996       4  ...  Are you ready for your MoJo Makeover? Ask me f...
1599997       4  ...  Happy 38th Birthday to my boo of alll time!!! ...
1599998       4  ...  happy #charitytuesday @theNSPCC @SparksCharity...

[1599999 rows x 6 columns]

**Data Description**

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599999 entries, 0 to 1599998
Data columns (total 6 columns):
Target       1599999 non-null int64
ID           1599999 non-null int64
Time_Info    1599999 non-null object
Query        1599999 non-null object
UN           1599999 non-null object
Comments     1599999 non-null object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

In [11]:
df.describe()

             Target            ID
count  1.599999e+06  1.599999e+06
mean   2.000001e+00  1.998818e+09
std    2.000001e+00  1.935757e+08
min    0.000000e+00  1.467811e+09
25%    0.000000e+00  1.956916e+09
50%    4.000000e+00  2.002102e+09
75%    4.000000e+00  2.177059e+09
max    4.000000e+00  2.329206e+09